### ISSUE TITLE
Feedback: Oppgave 5: Prosjekt Del B

### ISSUE THREAD

**Issue by webminz** [Oskarmo/Part_B2#1]
Hei! Godt jobbet med prosjekt del B. Du har klart å implementere et solid fundament som dekker viktige aspekter av oppgaven, spesielt med tanke på hvordan du har organisert logikken for å lagre og hente data fra databasen. Her er noen tilbakemeldinger på arbeidet ditt:

## Det du har gjort bra:

- Først og fremst, flott at du klarte å få alle testene til å kjøre suksessfullt. Dette er et godt tegn på at du har jobbet strukturert og målrettet mot oppgavenes krav. Kjempebra!

- Koden for å laste ned den komplette strukturen av smarthuset (`load_smarthouse_deep`) fra databasen er veldig ryddig og følger god praksis med å bruke `fetchall()` for å hente data spørringer. Dette viser at du har en solid forståelse av databasens interaksjon med Python.

- Bruk av klasser og arv i `domain.py` er godt utført. Det viser at du forstår objekt-orientert programmeringskonsepter godt. Dette er spesielt synlig ved din bruk av `Actuator` og `Sensor` klasser, samt metodene for å slå dem på og av.

## Potensielle feil og forbedringsområder:

- Når det gjelder `update_actuator_state`, er det veldig bra at du bruker `CREATE TABLE IF NOT EXISTS` for å sikre at tabellen eksisterer før du prøver å legge inn data. Det er imidlertid viktig å huske at denne koden vil kjøre hver gang metoden blir kalt, som kan være unødvendig etter at tabellen først er opprettet. Vurder om tabellen virkelig trenger å sjekkes / opprettes hver gang, eller om dette kan gjøres en gang ved initialisering.

- I `calc_hours_with_humidity_above` har du gjort noen antagelser om hvilke timer som skal returneres. Selv om dette kan fungere for de spesifikke testene, er det viktig å sørge for at funksjonen generelt kan håndtere ulike inndata og situasjoner korrekt. Det ville vært ideelt å finne en løsning som dynamisk identifiserer timer basert på faktiske målinger fra databasen, uten å "jukse" ved å bruke forventede verdier.

## Tips til videre forbedringer:

- For å optimalisere kode ytterligere, kunne du vurdert å benytte `with`-kontekstmanagere når du jobber med databaseforbindelser. Dette sikrer at forbindelsen lukkes på en ryddig måte, selv om det oppstår feil under databaseoperasjoner.

- Det kan også være nyttig å utforske mer avanserte SQL-funksjoner og -teknikker for å gjøre spørringene dine mer kompakte og effektive, spesielt for de statistiske beregningene i `calc_avg_temperatures_in_room` og `calc_hours_with_humidity_above`.

Generelt har du gjort et meget godt arbeid på dette prosjektet. Fortsett med det gode arbeidet og utforskningen av databaser!

Du kan bare _lukke_ dette "issue" som _løst_ når du har lest gjenomm den :wink:

**Comment by Oskarmo** [comment]
takk for tilbakemelding :)
